name: Auto Checkin

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */4 */1 * *"

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: User Data Cache
              uses: actions/cache@v4
              with:
                  path: ./user_data.json
                  key: ${{ runner.os }}

            - name: Build Cache
              uses: actions/cache@v4
              with:
                  path: ./main.js
                  key: ${{ runner.os }}-${{ hashFiles('main.ts') }}

            - name: Secrets
              run: echo '${{ secrets.USER_DATA }}' > secrets.json

            - name: Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install
              run: npm i

            - name: Build
              run: |
                  if ! test -e "./main.js"; then
                      tsc main.ts
                  fi

            - name: Run script
              run: node main.js
