name: Auto Checkin

on:
    workflow_dispatch:
    schedule:
        - cron: "30 5 * * *"

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/cache@v4
              with:
                  path: ./
                  key: ${{ runner.os }}-${{ hashFiles('main.ts') }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - run: npm install

            - name: Setup Secrets
              run: echo '${{ secrets.USER_DATA }}' > secrets.json

            - run: tsc main.ts

            - run: node main.js
