name: Auto Checkin

on:
    workflow_dispatch:
    schedule:
        - cron: "30 5 * * *"

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/cache@v4
              with:
                  path: |
                      ./main.js
                      ./secrets.json
                      ./user_data.json
                  key: ${{ runner.os }}-${{ hashFiles('main.ts') }}

            - name: Setup Secrets
              run: |
                  if [! -e "./secrets.json"]; then
                      echo '${{ secrets.USER_DATA }}' > secrets.json
                  fi

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - run: npm i

            - run: |
                  if [! -e "./main.js"]; then
                      tsc main.ts
                  fi

            - run: node main.js
